version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres-dunno
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5433:5432
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
